/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/application-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Application Details
         * @description Correct the title and company of an application.
         */
        post: operations["application_details_api_application_details_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/application-document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Application Document
         * @description Return one document of a job's application as a download; 404 for anything else.
         */
        get: operations["application_document_api_application_document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/application-listing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Application Listing
         * @description Attach a new listing to an existing application.
         */
        post: operations["application_listing_api_application_listing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/application-salary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Application Salary
         * @description Change the salary expectation of an application.
         */
        post: operations["application_salary_api_application_salary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Applications
         * @description Return open and completed applications with their statistics.
         */
        get: operations["applications_api_applications_get"];
        put?: never;
        /**
         * Application Start
         * @description Record an application with its documents (a form upload) and salary expectation.
         */
        post: operations["application_start_api_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fact-sheet-rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fact Sheet Rerun
         * @description Ask the next agent run for a new fact sheet; the review calls no model itself.
         */
        post: operations["fact_sheet_rerun_api_fact_sheet_rerun_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * History Edit
         * @description Correct one step in an application's history.
         */
        post: operations["history_edit_api_history_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * History Delete
         * @description Remove one step from an application's history.
         */
        post: operations["history_delete_api_history_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manual-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manual Import
         * @description Import one listing from a URL the user pasted.
         */
        post: operations["manual_import_api_manual_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommendations
         * @description Return the review's cards; archived=1 returns only those of listings that went offline.
         */
        get: operations["recommendations_api_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Note
         * @description Save the user's note on a job; an empty one removes it.
         */
        post: operations["review_note_api_review_note_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Status
         * @description Decide on a job in the review.
         */
        post: operations["review_status_api_review_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Undo
         * @description Undo the latest "not interested" if nothing changed it since.
         */
        post: operations["review_undo_api_review_undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs
         * @description Return the newest finder run of each runner (cloud, hybrid, local) with its key figures.
         */
        get: operations["runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources
         * @description Return the display name of every source, keyed by its internal name.
         */
        get: operations["sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Status
         * @description Record a dated step of an application.
         */
        post: operations["status_api_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Application
         * @description One application with its timeline, documents and derived figures.
         */
        Application: {
            /** Active */
            active: boolean;
            /**
             * Agent Sources
             * @default []
             */
            agent_sources: string[];
            /** Applied On */
            applied_on?: string | null;
            /** Automatic No Response */
            automatic_no_response: boolean;
            /** Company */
            company: string;
            /** Days To Response */
            days_to_response?: number | null;
            /** Documents */
            documents: components["schemas"]["Document"][];
            /** Has Interview */
            has_interview: boolean;
            /** Has No Response */
            has_no_response: boolean;
            /** Has Offer */
            has_offer: boolean;
            /** Has Rejection */
            has_rejection: boolean;
            /** Has Response */
            has_response: boolean;
            /** Has Trial Day */
            has_trial_day: boolean;
            /** Has Withdrawal */
            has_withdrawal: boolean;
            /** Id */
            id: string;
            /** Last Appointment At */
            last_appointment_at?: string | null;
            /** Last Appointment Status */
            last_appointment_status?: string | null;
            /** Last Event On */
            last_event_on?: string | null;
            /** Next Appointment At */
            next_appointment_at?: string | null;
            /** Next Appointment Status */
            next_appointment_status?: string | null;
            /** Response On */
            response_on?: string | null;
            /** Review Note */
            review_note: string;
            /** Salary Expectation Eur */
            salary_expectation_eur?: number | null;
            /** Source Links */
            source_links: components["schemas"]["SourceLink"][];
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Workflow History */
            workflow_history: components["schemas"]["HistoryEvent-Output"][];
            /** Workflow Status */
            workflow_status: string;
        };
        /** ApplicationDetails */
        ApplicationDetails: {
            /** Company */
            company?: unknown;
            /** Job Id */
            job_id: string;
            /** Title */
            title?: unknown;
        };
        /** ApplicationListing */
        ApplicationListing: {
            /** Application Id */
            application_id: string;
            /** Job Id */
            job_id: string;
        };
        /** ApplicationSalary */
        ApplicationSalary: {
            /** Job Id */
            job_id: string;
            /** Salary Expectation Eur */
            salary_expectation_eur?: unknown;
            /**
             * Salary Period
             * @default year
             */
            salary_period: string;
        };
        /** ApplicationStatistics */
        ApplicationStatistics: {
            /** Average Response Days */
            average_response_days?: number | null;
            /** Completed */
            completed: number;
            /** Interviews */
            interviews: number;
            /** No Responses */
            no_responses: number;
            /** Offers */
            offers: number;
            /** Open */
            open: number;
            /** Rejections */
            rejections: number;
            /** Response Rate Percent */
            response_rate_percent: number;
            /** Response Time Samples */
            response_time_samples: number;
            /** Responses */
            responses: number;
            /** Total */
            total: number;
            /** Trial Days */
            trial_days: number;
            /** Withdrawals */
            withdrawals: number;
        };
        /** ApplicationsResponse */
        ApplicationsResponse: {
            /** Application Statuses */
            application_statuses: string[];
            /** Applications */
            applications: components["schemas"]["Application"][];
            /** Completed Applications */
            completed_applications: components["schemas"]["Application"][];
            statistics: components["schemas"]["ApplicationStatistics"];
            /** Workflow Statuses */
            workflow_statuses: string[];
        };
        /** Body_application_start_api_applications_post */
        Body_application_start_api_applications_post: {
            /** Cover Letter */
            cover_letter?: string | null;
            /** Job Id */
            job_id: string;
            /** Resume */
            resume?: string | null;
            /** Salary Expectation Eur */
            salary_expectation_eur?: string | null;
            /**
             * Salary Period
             * @default year
             */
            salary_period: string;
        };
        /**
         * CompanyApplication
         * @description An application at the card's company, for the review's hint.
         */
        CompanyApplication: {
            /** Open */
            open: boolean;
            /** Title */
            title: string;
            /** Workflow Status */
            workflow_status: string;
        };
        /** Document */
        Document: {
            /** Id */
            id?: string | null;
            /** Kind */
            kind?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * FactSheetInfo
         * @description The agent's fact sheet for a card, or why it stopped.
         */
        FactSheetInfo: {
            /** Complete */
            complete: boolean;
            /** Cost Eur */
            cost_eur: number;
            /** Created At */
            created_at: string;
            /** Model */
            model: string;
            /** Note */
            note?: string | null;
            /**
             * Outdated
             * @default []
             */
            outdated: string[];
            /** Retryable */
            retryable: boolean;
            /** Sheet */
            sheet?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryEdit */
        HistoryEdit: {
            /** Event Index */
            event_index: number;
            /** Job Id */
            job_id: string;
            /** Occurred On */
            occurred_on?: string | null;
            /** Previous Occurred On */
            previous_occurred_on?: string | null;
            /** Previous Scheduled For */
            previous_scheduled_for?: string | null;
            /** Previous Status */
            previous_status: string;
            /** Scheduled For */
            scheduled_for?: string | null;
            /** Workflow Status */
            workflow_status: string;
        };
        /** HistoryEvent */
        "HistoryEvent-Input": {
            /** Event Index */
            event_index: number;
            /** Job Id */
            job_id: string;
            /** Previous Occurred On */
            previous_occurred_on?: string | null;
            /** Previous Scheduled For */
            previous_scheduled_for?: string | null;
            /** Previous Status */
            previous_status: string;
        };
        /** HistoryEvent */
        "HistoryEvent-Output": {
            /** Event Index */
            event_index?: number | null;
            /** Occurred On */
            occurred_on?: string | null;
            /** Reason */
            reason?: string | null;
            /** Scheduled For */
            scheduled_for?: string | null;
            /** Status */
            status: string;
        };
        /** JobRequest */
        JobRequest: {
            /** Job Id */
            job_id: string;
        };
        /** ManualImport */
        ManualImport: {
            /** Url */
            url?: unknown;
        };
        /** RecommendationsResponse */
        RecommendationsResponse: {
            /** Recommendations */
            recommendations: components["schemas"]["ReviewCard"][];
            /** Route Origin */
            route_origin: string;
            /** Workflow Statuses */
            workflow_statuses: string[];
        };
        /**
         * ReviewCard
         * @description One card of the review: a job with its listings and the user's decision.
         */
        ReviewCard: {
            /**
             * Application Tracked
             * @default false
             */
            application_tracked: boolean;
            /**
             * Cache Stale
             * @default false
             */
            cache_stale: boolean;
            /**
             * Career Levels
             * @default []
             */
            career_levels: string[];
            /** Company */
            company?: string | null;
            /**
             * Company Applications
             * @default []
             */
            company_applications: components["schemas"]["CompanyApplication"][];
            /**
             * Current Snapshot Missing
             * @default false
             */
            current_snapshot_missing: boolean;
            /** Experience Level */
            experience_level?: string | null;
            /** Experience Rank */
            experience_rank?: number | null;
            fact_sheet?: components["schemas"]["FactSheetInfo"] | null;
            /**
             * Fact Sheet Rerun
             * @default false
             */
            fact_sheet_rerun: boolean;
            /** Fetched At */
            fetched_at?: string | null;
            /** First Seen At */
            first_seen_at?: string | null;
            /** Id */
            id: string;
            /**
             * International
             * @default false
             */
            international: boolean;
            /**
             * Is New
             * @default false
             */
            is_new: boolean;
            /** Location Precheck */
            location_precheck?: string | null;
            /**
             * Locations
             * @default []
             */
            locations: string[];
            /** Match Percent */
            match_percent?: number | null;
            /** Prefilter Warning */
            prefilter_warning?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Recommendation Id */
            recommendation_id?: string | null;
            /** Remote Percentage */
            remote_percentage?: number | null;
            /**
             * Review Note
             * @default
             */
            review_note: string;
            /** Role Group */
            role_group?: string | null;
            /** Role Label */
            role_label?: string | null;
            /**
             * Source Links
             * @default []
             */
            source_links: components["schemas"]["SourceLink"][];
            /** Title */
            title: string;
            /**
             * Url
             * @default
             */
            url: string;
            /** Work Mode */
            work_mode?: string | null;
            /** Workflow Status */
            workflow_status: string;
        };
        /** ReviewDecision */
        ReviewDecision: {
            /** Job Id */
            job_id: string;
            /** Workflow Status */
            workflow_status: string;
        };
        /** ReviewNote */
        ReviewNote: {
            /** Job Id */
            job_id: string;
            /** Review Note */
            review_note?: unknown;
        };
        /** ReviewUndo */
        ReviewUndo: {
            /** Expected Status */
            expected_status: string;
            /** Job Id */
            job_id: string;
        };
        /**
         * Run
         * @description The newest finder run of one runner with its key figures.
         */
        Run: {
            /** Finished At */
            finished_at?: string | null;
            /** Jobs New */
            jobs_new?: number | null;
            /** Jobs Total */
            jobs_total?: number | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "running" | "finished" | "failed";
            /** Review New */
            review_new?: number | null;
            /** Run Id */
            run_id: string;
            /**
             * Runner
             * @enum {string}
             */
            runner: "cloud" | "hybrid" | "local";
            /** Sources Failed */
            sources_failed?: number | null;
            /** Sources Partial */
            sources_partial?: number | null;
            /** Started At */
            started_at: string;
        };
        /** RunsResponse */
        RunsResponse: {
            /** Runs */
            runs: components["schemas"]["Run"][];
        };
        /** SourceLink */
        SourceLink: {
            /** Source */
            source: string;
            /** Url */
            url: string;
        };
        /** SourcesResponse */
        SourcesResponse: {
            /** Labels */
            labels: {
                [key: string]: string;
            };
        };
        /** StatusChange */
        StatusChange: {
            /** Job Id */
            job_id: string;
            /** Occurred On */
            occurred_on?: string | null;
            /** Scheduled For */
            scheduled_for?: string | null;
            /** Workflow Status */
            workflow_status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    application_details_api_application_details_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationDetails"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_document_api_application_document_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    application_listing_api_application_listing_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationListing"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_salary_api_application_salary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationSalary"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    applications_api_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationsResponse"];
                };
            };
        };
    };
    application_start_api_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_application_start_api_applications_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fact_sheet_rerun_api_fact_sheet_rerun_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_edit_api_history_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_delete_api_history_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryEvent-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_import_api_manual_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_api_recommendations_get: {
        parameters: {
            query?: {
                archived?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_note_api_review_note_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewNote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_status_api_review_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_undo_api_review_undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewUndo"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
        };
    };
    sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
        };
    };
    status_api_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
