"""Personal matching profile for deterministic job scoring.

Sources only collect job data. This module describes which roles, skills and
working conditions fit the current profile.
"""

# The five score categories add up to exactly 100 points.
SCORE_LIMITS = {
    "role": 30,
    "skills": 25,
    "experience": 25,
    "location": 15,
    "profile": 5,
}

ROLE_GROUPS = [
    {
        "id": "python_ai_data",
        "label": "Python/AI/Data-Kernrolle",
        "points": 30,
        "patterns": [
            ["python", "developer"],
            ["python", "dev"],
            ["python", "entwickler"],
            ["python", "engineer"],
            ["ai", "engineer"],
            ["ai", "developer"],
            ["ai", "entwickler"],
            ["ki", "engineer"],
            ["ki", "entwickler"],
            ["ki", "experte"],
            ["machine learning", "engineer"],
            ["ml", "engineer"],
            ["prompt", "engineer"],
            ["data", "analyst"],
            ["daten", "analyst"],
            ["datenanalyst"],
            ["data", "engineer"],
            ["daten", "ingenieur"],
            ["data", "scientist"],
        ],
    },
    {
        "id": "ai_business_analysis",
        "label": "KI Business Analysis",
        "points": 24,
        "patterns": [
            ["ai", "business analyst"],
            ["ki", "business analyst"],
            ["artificial intelligence", "business analyst"],
        ],
    },
    {
        "id": "junior_sap",
        "label": "SAP-Einstiegsrolle",
        "points": 14,
        "entry_only": True,
        "patterns": [
            ["sap", "consultant"],
            ["sap", "berater"],
            ["sap", "entwickler"],
            ["sap", "developer"],
            ["abap", "entwickler"],
            ["abap", "developer"],
        ],
    },
    {
        "id": "software_development",
        "label": "Softwareentwicklung",
        "points": 27,
        "patterns": [
            ["backend", "developer"],
            ["backend", "dev"],
            ["backend", "entwickler"],
            ["backend", "engineer"],
            ["fullstack", "developer"],
            ["fullstack", "dev"],
            ["fullstack", "entwickler"],
            ["fullstack", "engineer"],
            ["full stack", "developer"],
            ["full stack", "dev"],
            ["full stack", "entwickler"],
            ["full stack", "engineer"],
            ["software", "developer"],
            ["software", "dev"],
            ["software", "entwickler"],
            ["softwareentwickler"],
            ["software", "engineer"],
            ["anwendungsentwickler"],
            ["application", "developer"],
            ["frontend", "developer"],
            ["frontend", "engineer"],
            ["frontend", "entwickler"],
            ["web", "developer"],
            ["webentwickler"],
            ["it", "entwickler"],
        ],
    },
    {
        "id": "testing",
        "label": "Software-Testautomatisierung/QA",
        "points": 23,
        "patterns": [
            ["test automation", "engineer"],
            ["testautomatisierung"],
            ["software test", "engineer"],
            ["software", "tester"],
            ["softwaretester"],
            ["qa", "engineer"],
            ["quality assurance", "engineer"],
            ["verification", "engineer"],
        ],
    },
    {
        "id": "technical_consulting",
        "label": "Technisches IT-Consulting",
        "points": 23,
        "patterns": [
            ["it", "consultant"],
            ["technical", "consultant"],
            ["software", "consultant"],
            ["data", "consultant"],
            ["ai", "consultant"],
            ["ki", "consultant"],
            ["cloud", "consultant"],
            ["security", "consultant"],
            ["it", "berater"],
            ["technischer", "berater"],
        ],
    },
    {
        "id": "infrastructure_automation",
        "label": "Infrastruktur-Automatisierung",
        "points": 20,
        "context_keywords": [
            "infrastructure as code",
            "infrastrukturautomatisierung",
            "infrastructure operations",
            "terraform",
            "ansible",
            "kubernetes",
            "deployment",
            "ci/cd",
            "devops",
            "cloud infrastructure",
        ],
        "excluded_context_keywords": [
            "rpa",
            "uipath",
            "power automate",
            "prozessautomatisierung",
            "robotic process automation",
        ],
        "patterns": [
            ["automation", "engineer"],
            ["automationsentwickler"],
            ["automatisierungsentwickler"],
        ],
    },
    {
        "id": "rpa_automation",
        "label": "RPA/Prozessautomatisierung",
        "points": 14,
        "context_keywords": [
            "rpa",
            "uipath",
            "power automate",
            "prozessautomatisierung",
            "robotic process automation",
        ],
        "patterns": [
            ["automation", "engineer"],
            ["automationsentwickler"],
            ["automatisierungsentwickler"],
            ["rpa", "developer"],
            ["rpa", "entwickler"],
            ["rpa", "consultant"],
        ],
    },
    {
        "id": "junior_modern_workplace",
        "label": "Junior Microsoft Cloud/Modern Workplace",
        "points": 14,
        "entry_only": True,
        "context_keywords": [
            "automation",
            "automatisierung",
            "powershell",
            "cloud",
            "copilot",
            "ai",
            "ki",
        ],
        "patterns": [
            ["modern workplace", "engineer"],
            ["microsoft 365", "consultant"],
            ["microsoft 365", "engineer"],
            ["m365", "consultant"],
            ["m365", "engineer"],
        ],
    },
    {
        "id": "junior_requirements",
        "label": "Junior Requirements/Business Analysis",
        "points": 14,
        "entry_only": True,
        "patterns": [
            ["requirements", "engineer"],
            ["requirement", "engineer"],
            ["product owner"],
            ["business", "analyst"],
        ],
    },
    {
        "id": "junior_administration",
        "label": "Junior IT-Administration mit Technikfokus",
        "points": 12,
        "entry_only": True,
        "context_keywords": [
            "automation",
            "automatisierung",
            "powershell",
            "cloud",
            "security",
            "sicherheit",
            "network",
            "netzwerk",
            "devops",
        ],
        "patterns": [
            ["systemadministrator"],
            ["system administrator"],
            ["it-administrator"],
            ["it administrator"],
            ["netzwerkadministrator"],
            ["network administrator"],
        ],
    },
    {
        "id": "infrastructure",
        "label": "DevOps/Cloud/Security/Network",
        "points": 20,
        "patterns": [
            ["devops", "engineer"],
            ["devops", "entwickler"],
            ["cloud", "engineer"],
            ["cloud", "entwickler"],
            ["security", "engineer"],
            ["security", "entwickler"],
            ["network", "engineer"],
            ["netzwerk", "engineer"],
            ["netzwerk", "spezialist"],
            ["site reliability", "engineer"],
            ["database reliability", "engineer"],
            ["platform operations", "engineer"],
            ["sysops", "engineer"],
            ["netops", "engineer"],
            ["cloud", "specialist"],
            ["devops"],
        ],
    },
    {
        "id": "architecture",
        "label": "Software-Architektur",
        "points": 20,
        "patterns": [
            ["software", "architect"],
            ["software", "architekt"],
        ],
    },
    {
        "id": "trainee",
        "label": "Technisches Traineeprogramm",
        "points": 23,
        "patterns": [
            ["trainee", "it"],
            ["trainee", "software"],
            ["trainee", "data"],
            ["trainee", "ai"],
            ["trainee", "ki"],
        ],
    },
]

SKILL_GROUPS = [
    {
        "id": "python",
        "label": "Python",
        "points": 10,
        "keywords": ["python"],
    },
    {
        "id": "ai_ml",
        "label": "AI/ML/RAG/Agenten",
        "points": 10,
        "keywords": [
            "ai",
            "ki",
            "ml",
            "artificial intelligence",
            "machine learning",
            "llm",
            "large language model",
            "rag",
            "agentic",
            "ki-agent",
            "ki agent",
            "ai agent",
        ],
    },
    {
        "id": "data",
        "label": "Data/Analytics",
        "points": 7,
        "keywords": [
            "data analyst",
            "data analytics",
            "data engineer",
            "data science",
            "datenanalyse",
            "datenanalyst",
            "business intelligence",
            "zeitreihe",
            "time series",
        ],
    },
    {
        "id": "testing",
        "label": "Testautomatisierung",
        "points": 6,
        "keywords": [
            "test automation",
            "testautomatisierung",
            "playwright",
            "jest",
            "mocha",
            "chai",
            "unit-test",
            "unit test",
            "api-test",
            "api test",
            "end-to-end",
            "e2e",
        ],
    },
    {
        "id": "javascript",
        "label": "JavaScript/TypeScript/Node.js",
        "points": 5,
        "keywords": ["javascript", "typescript", "node.js", "nodejs"],
    },
    {
        "id": "java",
        "label": "Java",
        "points": 4,
        "keywords": ["java"],
    },
    {
        "id": "devops",
        "label": "DevOps/Cloud-Automatisierung",
        "points": 5,
        "keywords": [
            "ci/cd",
            "continuous integration",
            "docker",
            "kubernetes",
            "terraform",
            "infrastructure as code",
            "ansible",
            "deployment",
            "automatisierung",
            "automation",
        ],
    },
    {
        "id": "security",
        "label": "Security/Network",
        "points": 4,
        "keywords": [
            "cybersecurity",
            "cyber security",
            "it-security",
            "informationssicherheit",
            "network security",
            "firewall",
        ],
    },
    {
        "id": "web_api",
        "label": "Web/API",
        "points": 3,
        "keywords": ["rest api", "rest-api", "backend", "webanwendung", "web application"],
    },
]

# Roles and employment types that are incompatible with an entry-level search.
BLOCKED_TITLE_WORDS = [
    "senior",
    "lead",
    "principal",
    "head",
    "manager",
    "testmanager",
    "test manager",
    "werkstudent",
    "working student",
    "praktikum",
    "praktikant",
    "thesis",
    "abschlussarbeit",
    "bachelorarbeit",
    "professur",
    "professor",
    "freelance",
    "freelancer",
    "freiberuflich",
    "quereinstieg",
    "helpdesk",
    "service desk",
    "first level support",
    "1st level support",
    "second level support",
    "2nd level support",
    "it-support",
    "supportmitarbeiter",
    "it-systembetreuer",
    "it-systembetreuung",
    "lohnmigration",
    "orbis",
    "anwendungsbetreuer",
]

ADMIN_TITLE_WORDS = [
    "systemadministrator",
    "system administrator",
    "it-administrator",
    "it administrator",
    "netzwerkadministrator",
    "network administrator",
]

MODERN_WORKPLACE_TITLE_WORDS = [
    "modern workplace",
    "microsoft 365",
    "m365",
]

# These technologies are excluded only when the title makes them the role's
# explicit core and no supported core technology appears in the title.
UNSUPPORTED_TITLE_TECHNOLOGIES = [
    "c#",
    ".net",
    "c++",
    "cobol",
    "salesforce",
    "go",
    "golang",
    "embedded",
    "abap",
    "sps",
]

SUPPORTED_TITLE_TECHNOLOGIES = [
    "python",
    "java",
    "javascript",
    "typescript",
    "node.js",
    "ai",
    "ki",
    "machine learning",
    "data",
]

BLOCKED_FOCUS_KEYWORDS = ["sap", "abap", "s/4hana", "s4hana", "sps"]

EXPLICIT_FOCUS_PHRASES = [
    "schwerpunkt {keyword}",
    "fokus {keyword}",
    "{keyword} entwickler",
    "{keyword}-entwickler",
    "{keyword} developer",
    "{keyword} consultant",
    "{keyword} berater",
]

# Approximate 30 km local area around Exampletown (Wasserkuppe).
LOCAL_PLACES = [
    "exampletown",
    "fulda",
    "kuenzell",
    "kunzell",
    "eichenzell",
    "petersberg",
    "gersfeld",
    "ebersburg",
    "dipperz",
    "hofbieber",
    "hilders",
    "ehrenberg",
    "tann",
    "motten",
    "kalbach",
    "neuhof",
    "hosenfeld",
]

GERMANY_LOCATION_WORDS = [
    "deutschland",
    "germany",
    "bundesweit",
    "deutschlandweit",
]

FOREIGN_ONLY_LOCATION_WORDS = [
    "portugal",
    "spanien",
    "spain",
    "frankreich",
    "france",
    "italien",
    "italy",
    "oesterreich",
    "austria",
    "schweiz",
    "switzerland",
    "poland",
    "polen",
    "netherlands",
    "niederlande",
    "united kingdom",
    "uk only",
]

ENTRY_LEVEL_WORDS = [
    "junior",
    "entry level",
    "entry-level",
    "berufseinsteiger",
    "graduate",
    "absolvent",
    "trainee",
    "keine berufserfahrung erforderlich",
    "ohne berufserfahrung",
    "0 jahre erfahrung",
]

FIRST_EXPERIENCE_PHRASES = [
    "erste erfahrung",
    "erste berufserfahrung",
    "erste praktische erfahrung",
    "erste projekterfahrung",
]

OPTIONAL_EXPERIENCE_PHRASES = [
    "wuenschenswert",
    "von vorteil",
    "ein plus",
    "waere ideal",
    "waeren gut",
    "hilfreich",
    "kein muss",
    "nicht erforderlich",
    "nicht notwendig",
]

STRONG_EXPERIENCE_PHRASES = [
    "mehrjaehrige berufserfahrung",
    "mehrjaehrige erfahrung",
    "fundierte berufserfahrung",
    "fundierte erfahrung",
    "einschlaegige berufserfahrung",
    "einschlaegige erfahrung",
]

PROFILE_DOMAIN_KEYWORDS = [
    "sensordaten",
    "sensor data",
    "zeitreihe",
    "time series",
    "industrial data",
    "industriedaten",
    "iot",
    "industrie 4.0",
]

HIGH_TRAVEL_PHRASES = [
    "hohe reisebereitschaft",
    "uneingeschraenkte reisebereitschaft",
    "deutschlandweite reisebereitschaft",
    "bundesweite reisebereitschaft",
    "regelmaessige dienstreisen deutschlandweit",
    "travel activity of 80%",
    "80% travel",
    "travel up to 80%",
]

MANDATORY_ADVANCED_DEGREE_PATTERNS = [
    r"(?:masterabschluss|masterstudium)[^.]{0,50}(?:erforderlich|vorausgesetzt|required|must)",
    r"(?:erforderlich|vorausgesetzt|required|must)[^.]{0,50}(?:masterabschluss|masterstudium)",
    r"(?:promotion|doktorgrad|phd)[^.]{0,50}(?:erforderlich|vorausgesetzt|required|must)",
    r"(?:erforderlich|vorausgesetzt|required|must)[^.]{0,50}(?:promotion|doktorgrad|phd)",
]

SALARY_TARGET = 83_000
SALARY_MINIMUM = 73_000
