"""Personal matching profile for deterministic job scoring.

Sources only collect job data. This module describes which roles, skills and
working conditions fit the current profile.
"""

# The five score categories add up to exactly 100 points.
SCORE_LIMITS = {
    "role": 30,
    "skills": 25,
    "experience": 25,
    "location": 15,
    "profile": 5,
}

# The LLM extracts these language-independent role families from job tasks.
# Python uses the personal priority here only for the final fit dimensions.
ROLE_FAMILY_FIT_RATINGS = {
    "ai_ml": "excellent",
    "data": "good",
    "backend": "good",
    "frontend": "good",
    "fullstack": "good",
    "software_development": "good",
    "consulting_business_analysis": "good",
    "devops_cloud": "partial",
    "security_network": "partial",
    "qa_testing": "partial",
    "sap_erp": "weak",
    "system_administration_support": "weak",
    "other": "conflict",
}

ROLE_GROUPS = [
    {
        "id": "python_ai_data",
        "label": "Python/AI/Data-Kernrolle",
        "points": 30,
        "patterns": [
            ["python", "developer"],
            ["python", "dev"],
            ["python", "entwickler"],
            ["python", "engineer"],
            ["ai", "engineer"],
            ["ai", "developer"],
            ["ai", "entwickler"],
            ["ki", "engineer"],
            ["ki", "entwickler"],
            ["machine learning", "engineer"],
            ["ml", "engineer"],
            ["prompt", "engineer"],
            ["data", "analyst"],
            ["daten", "analyst"],
            ["datenanalyst"],
            ["data", "engineer"],
            ["daten", "ingenieur"],
            ["data", "scientist"],
        ],
    },
    {
        "id": "ai_business_analysis",
        "label": "KI Business Analysis",
        "points": 24,
        "patterns": [
            ["ai", "business analyst"],
            ["ki", "business analyst"],
            ["artificial intelligence", "business analyst"],
        ],
    },
    {
        "id": "junior_sap",
        "label": "SAP-Einstiegsrolle",
        "points": 14,
        "entry_only": True,
        "patterns": [
            ["sap", "consultant"],
            ["sap", "berater"],
            ["sap", "entwickler"],
            ["sap", "developer"],
            ["abap", "entwickler"],
            ["abap", "developer"],
        ],
    },
    {
        "id": "software_development",
        "label": "Softwareentwicklung",
        "points": 27,
        "patterns": [
            ["backend", "developer"],
            ["backend", "dev"],
            ["backend", "entwickler"],
            ["backend", "engineer"],
            ["fullstack", "developer"],
            ["fullstack", "dev"],
            ["fullstack", "entwickler"],
            ["fullstack", "engineer"],
            ["full stack", "developer"],
            ["full stack", "dev"],
            ["full stack", "entwickler"],
            ["full stack", "engineer"],
            ["software", "developer"],
            ["software", "dev"],
            ["software", "entwickler"],
            ["softwareentwickler"],
            ["software", "engineer"],
            ["anwendungsentwickler"],
            ["application", "developer"],
            ["frontend", "developer"],
            ["frontend", "engineer"],
            ["frontend", "entwickler"],
            ["web", "developer"],
            ["webentwickler"],
            ["it", "entwickler"],
        ],
    },
    {
        "id": "testing",
        "label": "Software-Testautomatisierung/QA",
        "points": 23,
        "patterns": [
            ["test automation", "engineer"],
            ["testautomatisierung"],
            ["software test", "engineer"],
            ["software", "tester"],
            ["softwaretester"],
            ["qa", "engineer"],
            ["quality assurance", "engineer"],
            ["verification", "engineer"],
        ],
    },
    {
        "id": "technical_consulting",
        "label": "Technisches IT-Consulting",
        "points": 23,
        "patterns": [
            ["it", "consultant"],
            ["technical", "consultant"],
            ["software", "consultant"],
            ["data", "consultant"],
            ["ai", "consultant"],
            ["ki", "consultant"],
            ["cloud", "consultant"],
            ["security", "consultant"],
            ["it", "berater"],
            ["technischer", "berater"],
        ],
    },
    {
        "id": "infrastructure_automation",
        "label": "Infrastruktur-Automatisierung",
        "points": 20,
        "context_keywords": [
            "infrastructure as code",
            "infrastrukturautomatisierung",
            "infrastructure operations",
            "terraform",
            "ansible",
            "kubernetes",
            "deployment",
            "ci/cd",
            "devops",
            "cloud infrastructure",
        ],
        "excluded_context_keywords": [
            "rpa",
            "uipath",
            "power automate",
            "prozessautomatisierung",
            "robotic process automation",
        ],
        "patterns": [
            ["automation", "engineer"],
            ["automationsentwickler"],
            ["automatisierungsentwickler"],
        ],
    },
    {
        "id": "rpa_automation",
        "label": "RPA/Prozessautomatisierung",
        "points": 14,
        "context_keywords": [
            "rpa",
            "uipath",
            "power automate",
            "prozessautomatisierung",
            "robotic process automation",
        ],
        "patterns": [
            ["automation", "engineer"],
            ["automationsentwickler"],
            ["automatisierungsentwickler"],
            ["rpa", "developer"],
            ["rpa", "entwickler"],
            ["rpa", "consultant"],
        ],
    },
    {
        "id": "junior_modern_workplace",
        "label": "Junior Microsoft Cloud/Modern Workplace",
        "points": 14,
        "entry_only": True,
        "context_keywords": [
            "automation",
            "automatisierung",
            "powershell",
            "cloud",
            "copilot",
            "ai",
            "ki",
        ],
        "patterns": [
            ["modern workplace", "engineer"],
            ["microsoft 365", "consultant"],
            ["microsoft 365", "engineer"],
            ["m365", "consultant"],
            ["m365", "engineer"],
        ],
    },
    {
        "id": "junior_requirements",
        "label": "Junior Requirements/Business Analysis",
        "points": 14,
        "entry_only": True,
        "patterns": [
            ["requirements", "engineer"],
            ["requirement", "engineer"],
            ["product owner"],
            ["business", "analyst"],
        ],
    },
    {
        "id": "junior_administration",
        "label": "Junior IT-Administration mit Technikfokus",
        "points": 12,
        "entry_only": True,
        "context_keywords": [
            "automation",
            "automatisierung",
            "powershell",
            "cloud",
            "security",
            "sicherheit",
            "network",
            "netzwerk",
            "devops",
        ],
        "patterns": [
            ["systemadministrator"],
            ["system administrator"],
            ["it-administrator"],
            ["it administrator"],
            ["netzwerkadministrator"],
            ["network administrator"],
        ],
    },
    {
        "id": "infrastructure",
        "label": "DevOps/Cloud/Security/Network",
        "points": 20,
        "patterns": [
            ["devops", "engineer"],
            ["devops", "entwickler"],
            ["cloud", "engineer"],
            ["cloud", "entwickler"],
            ["security", "engineer"],
            ["security", "entwickler"],
            ["network", "engineer"],
            ["netzwerk", "engineer"],
            ["netzwerk", "spezialist"],
            ["site reliability", "engineer"],
            ["database reliability", "engineer"],
            ["platform operations", "engineer"],
            ["sysops", "engineer"],
            ["netops", "engineer"],
            ["cloud", "specialist"],
            ["devops"],
        ],
    },
    {
        "id": "architecture",
        "label": "Software-Architektur",
        "points": 20,
        "patterns": [
            ["software", "architect"],
            ["software", "architekt"],
        ],
    },
    {
        "id": "trainee",
        "label": "Technisches Traineeprogramm",
        "points": 23,
        "patterns": [
            ["trainee", "it"],
            ["trainee", "software"],
            ["trainee", "data"],
            ["trainee", "ai"],
            ["trainee", "ki"],
        ],
    },
]

# Broad fallback used only to keep clearly technical IT jobs in the inexpensive
# prefilter. Personal interest and technology fit are decided by the LLM.
GENERAL_IT_TITLE_KEYWORDS = [
    "developer",
    "entwickler",
    "software",
    "informatik",
    "fachinformatiker",
    "it",
    "system engineer",
    "systemingenieur",
    "systemadministrator",
    "administrator",
    "data",
    "daten",
    "cloud",
    "devops",
    "network",
    "netzwerk",
    "cyber",
    "it-security",
    "programmierer",
    "programmer",
    "architect",
    "architekt",
    "product owner",
    "requirements",
    "technical consultant",
    "technischer consultant",
    "sap",
    "abap",
    "salesforce",
    "microsoft 365",
    "modern workplace",
    "helpdesk",
    "support specialist",
    "support spezialist",
    "systembetreuer",
    "anwendungsbetreuer",
]

GENERAL_IT_ROLE = {
    "id": "general_it",
    "label": "Allgemeine IT-Rolle",
    "points": 10,
}

SKILL_GROUPS = [
    {
        "id": "python",
        "label": "Python",
        "points": 10,
        "keywords": ["python"],
    },
    {
        "id": "ai_ml",
        "label": "AI/ML/RAG/Agenten",
        "points": 10,
        "keywords": [
            "ai",
            "ki",
            "ml",
            "artificial intelligence",
            "machine learning",
            "llm",
            "large language model",
            "rag",
            "agentic",
            "ki-agent",
            "ki agent",
            "ai agent",
        ],
    },
    {
        "id": "data",
        "label": "Data/Analytics",
        "points": 7,
        "keywords": [
            "data analyst",
            "data analytics",
            "data engineer",
            "data science",
            "datenanalyse",
            "datenanalyst",
            "business intelligence",
            "zeitreihe",
            "time series",
        ],
    },
    {
        "id": "testing",
        "label": "Testautomatisierung",
        "points": 6,
        "keywords": [
            "test automation",
            "testautomatisierung",
            "playwright",
            "jest",
            "mocha",
            "chai",
            "unit-test",
            "unit test",
            "api-test",
            "api test",
            "end-to-end",
            "e2e",
        ],
    },
    {
        "id": "javascript",
        "label": "JavaScript/TypeScript/Node.js",
        "points": 5,
        "keywords": ["javascript", "typescript", "node.js", "nodejs"],
    },
    {
        "id": "java",
        "label": "Java",
        "points": 4,
        "keywords": ["java"],
    },
    {
        "id": "devops",
        "label": "DevOps/Cloud-Automatisierung",
        "points": 5,
        "keywords": [
            "ci/cd",
            "continuous integration",
            "docker",
            "kubernetes",
            "terraform",
            "infrastructure as code",
            "ansible",
            "deployment",
            "automatisierung",
            "automation",
        ],
    },
    {
        "id": "security",
        "label": "Security/Network",
        "points": 4,
        "keywords": [
            "cybersecurity",
            "cyber security",
            "it-security",
            "informationssicherheit",
            "network security",
            "firewall",
        ],
    },
    {
        "id": "web_api",
        "label": "Web/API",
        "points": 3,
        "keywords": ["rest api", "rest-api", "backend", "webanwendung", "web application"],
    },
]

# Roles and employment types that are incompatible with an entry-level search.
BLOCKED_TITLE_WORDS = [
    "senior",
    "experte",
    "expert",
    "lead",
    "principal",
    "head",
    "leitung",
    "leiter",
    "projektleiter",
    "projektmanager",
    "teamleiter",
    "abteilungsleiter",
    "manager",
    "testmanager",
    "test manager",
    "werkstudent",
    "working student",
    "praktikum",
    "praktikant",
    "thesis",
    "abschlussarbeit",
    "bachelorarbeit",
    "ausbildung",
    "auszubildende",
    "auszubildender",
    "auszubildenden",
    "azubi",
    "duales studium",
    "dual study",
    "professur",
    "professor",
    "freelance",
    "freelancer",
    "freiberuflich",
]

# Approximate 30 km local area around Exampletown (Wasserkuppe).
LOCAL_PLACES = [
    "exampletown",
    "fulda",
    "kuenzell",
    "kunzell",
    "eichenzell",
    "petersberg",
    "gersfeld",
    "ebersburg",
    "dipperz",
    "hofbieber",
    "hilders",
    "ehrenberg",
    "tann",
    "motten",
    "kalbach",
    "neuhof",
    "hosenfeld",
]

GERMANY_LOCATION_WORDS = [
    "deutschland",
    "germany",
    "bundesweit",
    "deutschlandweit",
]

FOREIGN_ONLY_LOCATION_WORDS = [
    "portugal",
    "spanien",
    "spain",
    "frankreich",
    "france",
    "italien",
    "italy",
    "oesterreich",
    "austria",
    "schweiz",
    "switzerland",
    "poland",
    "polen",
    "netherlands",
    "niederlande",
    "united kingdom",
    "uk only",
]

ENTRY_LEVEL_WORDS = [
    "junior",
    "entry level",
    "entry-level",
    "berufseinsteiger",
    "graduate",
    "absolvent",
    "trainee",
    "keine berufserfahrung erforderlich",
    "ohne berufserfahrung",
    "0 jahre erfahrung",
]

# Body text needs stronger evidence than a generic mention of graduates or
# entry-level colleagues in the employer description.
BODY_ENTRY_LEVEL_PHRASES = [
    "keine berufserfahrung erforderlich",
    "ohne berufserfahrung",
    "0 jahre erfahrung",
    "berufseinsteiger willkommen",
    "geeignet fuer berufseinsteiger",
    "auch fuer berufseinsteiger",
    "du willst welche sammeln",
    "einstieg in die karriere",
]

FIRST_EXPERIENCE_PHRASES = [
    "erste erfahrung",
    "erste erfahrungen",
    "erste berufserfahrung",
    "erste berufliche erfahrungen",
    "erste praktische erfahrung",
    "erste praktische erfahrungen",
    "erste projekterfahrung",
]

OPTIONAL_EXPERIENCE_PHRASES = [
    "wuenschenswert",
    "von vorteil",
    "idealerweise",
    "ideally",
    "ein plus",
    "waere ideal",
    "waeren gut",
    "hilfreich",
    "kein muss",
    "nicht erforderlich",
    "nicht notwendig",
]

STRONG_EXPERIENCE_PHRASES = [
    "mehrjaehrige berufserfahrung",
    "mehrjaehrige erfahrung",
    "mehrjaehrige praktische erfahrung",
    "langjaehrige berufserfahrung",
    "langjaehrige erfahrung",
    "bereits berufserfahrung",
    "fundierte berufserfahrung",
    "fundierte erfahrung",
    "einschlaegige berufserfahrung",
    "einschlaegige erfahrung",
    "several years of experience",
    "multiple years of experience",
    "deep previous experience",
    "extensive experience",
    "proven professional experience",
    "demonstrated professional experience",
    "worked in a similar",
]

PROFILE_DOMAIN_KEYWORDS = [
    "sensordaten",
    "sensor data",
    "zeitreihe",
    "time series",
    "industrial data",
    "industriedaten",
    "iot",
    "industrie 4.0",
]

HIGH_TRAVEL_PHRASES = [
    "hohe reisebereitschaft",
    "uneingeschraenkte reisebereitschaft",
    "deutschlandweite reisebereitschaft",
    "bundesweite reisebereitschaft",
    "regelmaessige dienstreisen deutschlandweit",
    "travel activity of 80%",
    "80% travel",
    "travel up to 80%",
]

MANDATORY_ADVANCED_DEGREE_PATTERNS = [
    r"(?:masterabschluss|masterstudium)[^.]{0,50}(?:erforderlich|vorausgesetzt|required|must)",
    r"(?:erforderlich|vorausgesetzt|required|must)[^.]{0,50}(?:masterabschluss|masterstudium)",
    r"(?:promotion|doktorgrad|phd)[^.]{0,50}(?:erforderlich|vorausgesetzt|required|must)",
    r"(?:erforderlich|vorausgesetzt|required|must)[^.]{0,50}(?:promotion|doktorgrad|phd)",
]

SALARY_TARGET = 83_000
SALARY_MINIMUM = 73_000
